#!/usr/bin/env bash

# My custom space names for my 2 monitor setup. These names are used in some scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sub-layer=above manage=off
yabai -m rule --add app="^System Settings$" sub-layer=above manage=off
yabai -m rule --add app="^Finder$" sub-layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sub-layer=above manage=off
yabai -m rule --add app="^System Information$" sub-layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sub-layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^USB Display Device$" manage=off
yabai -m rule --add app="^Stickies$" manage=off

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 0 \
	bottom_padding 0 \
	left_padding 0 \
	right_padding 0 \
	window_gap 0 \
	layout bsp \
	mouse_modifier ctrl \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap
# window_animation_duration 0.0 \
# window_animation_frame_rate 120 \
# window_opacity_duration 0.0 \
# active_window_opacity 1.0 \
# normal_window_opacity 0.90 \

# script: If I close the active window, focus on any other visible window.
# yabai -m signal --add event=window_destroyed action="bash /Users/jesseskelton/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"

echo "yabai configuration loaded.."
